
const AliasedRPs = [
  "Microsoft.AAD",                     "Microsoft.AISupercomputer",
  "Microsoft.AVS",                     "Microsoft.AlertsManagement",
  "Microsoft.AnalysisServices",        "Microsoft.ApiManagement",
  "Microsoft.App",                     "Microsoft.AppConfiguration",
  "Microsoft.AppPlatform",             "Microsoft.Attestation",
  "Microsoft.Authorization",           "Microsoft.Automanage",
  "Microsoft.Automation",              "Microsoft.AzureActiveDirectory",
  "Microsoft.AzureArcData",            "Microsoft.AzureStackHCI",
  "Microsoft.Batch",                   "Microsoft.Blockchain",
  "Microsoft.Blueprint",               "Microsoft.BotService",
  "Microsoft.Cache",                   "Microsoft.Capacity",
  "Microsoft.Cdn",                     "Microsoft.Codespaces",
  "Microsoft.CognitiveServices",       "Microsoft.Compute",
  "Microsoft.ConnectedVMwarevSphere",  "Microsoft.Consumption",
  "Microsoft.ContainerInstance",       "Microsoft.ContainerRegistry",
  "Microsoft.ContainerService",        "Microsoft.CustomProviders",
  "Microsoft.DBforMariaDB",            "Microsoft.DBforMySQL",
  "Microsoft.DBforPostgreSQL",         "Microsoft.Dashboard",
  "Microsoft.DataBox",                 "Microsoft.DataBoxEdge",
  "Microsoft.DataCatalog",             "Microsoft.DataFactory",
  "Microsoft.DataLakeAnalytics",       "Microsoft.DataLakeStore",
  "Microsoft.DataMigration",           "Microsoft.DataProtection",
  "Microsoft.DataShare",               "Microsoft.Databricks",
  "Microsoft.Datadog",                 "Microsoft.DesktopVirtualization",
  "Microsoft.DevSpaces",               "Microsoft.DevTestLab",
  "Microsoft.DeviceUpdate",            "Microsoft.Devices",
  "Microsoft.DigitalTwins",            "Microsoft.DocumentDB",
  "Microsoft.EdgeOrder",               "Microsoft.EventGrid",
  "Microsoft.EventHub",                "Microsoft.ExtendedLocation",
  "Microsoft.Features",                "Microsoft.FluidRelay",
  "Microsoft.GuestConfiguration",      "Microsoft.HDInsight",
  "Microsoft.HealthBot",               "Microsoft.HealthcareApis",
  "Microsoft.HybridCompute",           "Microsoft.IoTCentral",
  "Microsoft.IoTSpaces",               "Microsoft.KeyVault",
  "Microsoft.Kubernetes",              "Microsoft.KubernetesConfiguration",
  "Microsoft.Kusto",                   "Microsoft.LabServices",
  "Microsoft.LoadTestService",         "Microsoft.Logic",
  "Microsoft.MachineLearning",         "Microsoft.MachineLearningServices",
  "Microsoft.Maintenance",             "Microsoft.ManagedIdentity",
  "Microsoft.ManagedServices",         "Microsoft.Management",
  "Microsoft.Maps",                    "Microsoft.Media",
  "Microsoft.Migrate",                 "Microsoft.MixedReality",
  "Microsoft.NetApp",                  "Microsoft.Network",
  "Microsoft.NotificationHubs",        "Microsoft.OffAzure",
  "Microsoft.OperationalInsights",     "Microsoft.OperationsManagement",
  "Microsoft.Portal",                  "Microsoft.PowerBI",
  "Microsoft.PowerBIDedicated",        "Microsoft.Purview",
  "Microsoft.RecoveryServices",        "Microsoft.RedHatOpenShift",
  "Microsoft.Relay",                   "Microsoft.Resources",
  "Microsoft.SaaS",                    "Microsoft.Scheduler",
  "Microsoft.Search",                  "Microsoft.Security",
  "Microsoft.SecurityInsights",        "Microsoft.ServiceBus",
  "Microsoft.ServiceFabric",           "Microsoft.ServiceLinker",
  "Microsoft.SignalRService",          "Microsoft.Singularity",
  "Microsoft.Solutions",               "Microsoft.Sql",
  "Microsoft.SqlVirtualMachine",       "Microsoft.StorSimple",
  "Microsoft.Storage",                 "Microsoft.StorageCache",
  "Microsoft.StorageSync",             "Microsoft.StreamAnalytics",
  "Microsoft.Subscription",            "Microsoft.Synapse",
  "Microsoft.TerraformOSS",            "Microsoft.TimeSeriesInsights",
  "Microsoft.VirtualMachineImages",    "Microsoft.Web",
  "Microsoft.Workloads",               "PolicyAliases.proj",
  "Providers.Test",                    "microsoft.aadiam",
  "microsoft.insights",                "microsoft.visualstudio"
];

const ServiceToRP = {
  "API Management": ["Microsoft.ApiManagement"],
  "App Service Certificates": ["Microsoft.CertificateRegistration"],
  "App Service": ["Microsoft.DomainRegistration", "Microsoft.Web"],
  "Application Gateway": ["Microsoft.Network"],
  "Automation": ["Microsoft.Automation"],
  "Autonomous Systems": ["Microsoft.AutonomousSystems"],
  "Azure Active Directory B2C": ["Microsoft.AzureActiveDirectory"],
  "Azure Active Directory Domain Services": ["Microsoft.AAD"],
  "Azure Active Directory": ["Microsoft.ADHybridHealthService"],
  "Azure Advisor": ["Microsoft.Advisor"],
  "Azure Analysis Services": ["Microsoft.AnalysisServices"],
  "Azure API for FHIR": ["Microsoft.HealthcareApis"],
  "Azure App Configuration": ["Microsoft.AppConfiguration"],
  "Azure Arc-enabled data services": ["Microsoft.AzureArcData"],
  "Azure Arc-enabled Kubernetes": ["Microsoft.Kubernetes"],
  "Azure Arc-enabled Kubernetes": ["Microsoft.KubernetesConfiguration"],
  "Azure Arc-enabled servers": ["Microsoft.HybridCompute"],
  "Azure Attestation Service": ["Microsoft.Attestation"],
  "Azure Bastion": ["Microsoft.Network"],
  "Azure Blockchain Service": ["Microsoft.Blockchain"],
  "Azure Blockchain Tokens": ["Microsoft.BlockchainTokens"],
  "Azure Blueprints": ["Microsoft.Blueprint"],
  "Azure Bot Service": ["Microsoft.BotService"],
  "Azure Cache for Redis": ["Microsoft.Cache"],
  "Azure Cognitive Search": ["Microsoft.Search"],
  "Azure Communication Services": ["Microsoft.Communication"],
  "Azure Container Apps": ["Microsoft.App"],
  "Azure Cosmos DB": ["Microsoft.DocumentDB"],
  "Azure Custom Providers": ["Microsoft.CustomProviders"],
  "Azure Data Box": ["Microsoft.DataBox"],
  "Azure Data Catalog": ["Microsoft.ProjectBabylon"],
  "Azure Data Explorer": ["Microsoft.Kusto"],
  "Azure Data Lake Storage Gen2": ["Microsoft.DataLakeStore"],
  "Azure Data Share": ["Microsoft.DataShare"],
  "Azure Database for MariaDB": ["Microsoft.DBforMariaDB"],
  "Azure Database for MySQL": ["Microsoft.DBforMySQL"],
  "Azure Database for PostgreSQL": ["Microsoft.DBforPostgreSQL"],
  "Azure Database Migration Service": ["Microsoft.DataMigration"],
  "Azure Databricks": ["Microsoft.Databricks"],
  "Azure DDoS Protection": ["Microsoft.Network"],
  "Azure Dedicated HSM": ["Microsoft.HardwareSecurityModules"],
  "Azure Dev Spaces": ["Microsoft.DevSpaces"],
  "Azure DevOps": ["Microsoft.DevOps","microsoft.visualstudio","Microsoft.VSOnline"],
  "Azure Digital Twins": ["Microsoft.DigitalTwins"],
  "Azure Digital Twins": ["Microsoft.IoTSpaces"],
  "Azure DNS": ["Microsoft.Network"],
  "Azure ExpressRoute": ["Microsoft.Network"],
  "Azure Firewall": ["Microsoft.Network"],
  "Azure Front Door Service": ["Microsoft.Network"],
  "Azure Functions": ["Microsoft.Web"],
  "Azure HPC Cache": ["Microsoft.StorageCache"],
  "Azure Image Builder": ["Microsoft.VirtualMachineImages"],
  "Azure Import/Export": ["Microsoft.ImportExport"],
  "Azure IoT Central": ["Microsoft.IoTCentral"],
  "Azure IoT Hub Device Provisioning Service": ["Microsoft.Devices"],
  "Azure IoT Hub": ["Microsoft.Devices"],
  "Azure Kubernetes Service (AKS)": ["Microsoft.ContainerService"],
  "Azure Lab Services": ["Microsoft.DevTestLab","Microsoft.LabServices"],
  "Azure Lighthouse": ["Microsoft.ManagedServices"],
  "Azure Machine Learning": ["Microsoft.MachineLearningServices"],
  "Azure Maintenance": ["Microsoft.Maintenance"],
  "Azure Managed Applications": ["Microsoft.Solutions"],
  "Azure Maps": ["Microsoft.Maps"],
  "Azure Migrate": ["Microsoft.Migrate","Microsoft.OffAzure"],
  "Azure Monitor": ["Microsoft.AlertsManagement","Microsoft.ChangeAnalysis","Microsoft.Insights","Microsoft.Intune","Microsoft.OperationalInsights","Microsoft.OperationsManagement","Microsoft.WorkloadMonitor"],
  "Azure NetApp Files": ["Microsoft.NetApp"],
  "Azure Notebooks": ["Microsoft.Notebooks"],
  "Azure Peering Service": ["Microsoft.Peering"],
  "Azure Policy": ["Microsoft.GuestConfiguration","Microsoft.PolicyInsights"],
  "Azure portal": ["Microsoft.Portal"],
  "Azure Private 5G Core": ["Microsoft.MobileNetwork"],
  "Azure Private Link": ["Microsoft.Network"],
  "Azure Quantum": ["Microsoft.Quantum"],
  "Azure Red Hat OpenShift": ["Microsoft.RedHatOpenShift"],
  "Azure Relay": ["Microsoft.Relay"],
  "Azure Resource Graph": ["Microsoft.ResourceGraph"],
  "Azure Resource Manager": ["Microsoft.Authorization","Microsoft.Features","Microsoft.Resources"],
  "Azure Route Server": ["Microsoft.Network"],
  "Azure Serial Console for Windows": ["Microsoft.SerialConsole"],
  "Azure Service Health": ["Microsoft.ResourceHealth"],
  "Azure SignalR Service": ["Microsoft.SignalRService"],
  "Azure Site Recovery": ["Microsoft.RecoveryServices"],
  "Azure Spatial Anchors": ["Microsoft.MixedReality"],
  "Azure Spring Apps": ["Microsoft.AppPlatform","Microsoft.Microservices4Spring"],
  "Azure SQL Database": ["Microsoft.Sql"],
  "Azure SQL Managed Instance": ["Microsoft.Sql"],
  "Azure Stack Edge": ["Microsoft.DataBoxEdge"],
  "Azure Stack HCI": ["Microsoft.AzureStackHCI"],
  "Azure Stream Analytics": ["Microsoft.StreamAnalytics"],
  "Azure Synapse Analytics": ["Microsoft.Sql","Microsoft.Synapse"],
  "Azure Time Series Insights": ["Microsoft.TimeSeriesInsights"],
  "Azure Virtual Desktop": ["Microsoft.DesktopVirtualization"],
  "Azure VMware Solution by CloudSimple": ["Microsoft.VMwareCloudSimple"],
  "Azure VMware Solution": ["Microsoft.AVS","Microsoft.VMware"],
  "Batch": ["Microsoft.Batch"],
  "Bing Maps": ["Microsoft.BingMaps"],
  "Classic deployment model migration": ["Microsoft.ClassicInfrastructureMigrate"],
  "Classic deployment model storage": ["Microsoft.ClassicStorage"],
  "Classic deployment model virtual machine": ["Microsoft.ClassicCompute"],
  "Classic deployment model virtual network": ["Microsoft.ClassicNetwork"],
  "Classic deployment model": ["Microsoft.ClassicSubscription"],
  "Cognitive Services": ["Microsoft.CognitiveServices"],
  "Container Instances": ["Microsoft.ContainerInstance"],
  "Container Registry": ["Microsoft.ContainerRegistry"],
  "Content Delivery Network": ["Microsoft.Cdn"],
  "core": ["Microsoft.Addons","Microsoft.AzureStack","Microsoft.Capacity","Microsoft.Commerce","Microsoft.Marketplace","Microsoft.MarketplaceApps","Microsoft.MarketplaceOrdering","Microsoft.SaaS","Microsoft.Services","Microsoft.Subscription","microsoft.support"],
  "Cost Management and Billing": ["Microsoft.Billing"],
  "Cost Management": ["Microsoft.Consumption","Microsoft.CostManagement","Microsoft.CostManagementExports"],
  "Customer Lockbox for Microsoft Azure": ["Microsoft.CustomerLockbox"],
  "Data Catalog": ["Microsoft.DataCatalog"],
  "Data Factory": ["Microsoft.DataFactory"],
  "Data Lake Analytics": ["Microsoft.DataLakeAnalytics"],
  "Data Protection": ["Microsoft.DataProtection"],
  "Device Update for IoT Hub": ["Microsoft.DeviceUpdate"],
  "Enterprise Knowledge Graph": ["Microsoft.EnterpriseKnowledgeGraph"],
  "Event Grid": ["Microsoft.EventGrid"],
  "Event Hubs": ["Microsoft.EventHub"],
  "Extended Security Updates": ["Microsoft.WindowsESU"],
  "HDInsight": ["Microsoft.HDInsight"],
  "Healthcare APIs": ["Microsoft.HealthcareApis"],
  "Key Vault": ["Microsoft.KeyVault"],
  "License": ["Microsoft.SoftwarePlan"],
  "Lifecycle Services": ["Microsoft.DynamicsLcs"],
  "Load Balancer": ["Microsoft.Network"],
  "Logic Apps": ["Microsoft.Logic"],
  "Machine Learning Studio": ["Microsoft.MachineLearning"],
  "Managed identities for Azure resources": ["Microsoft.ManagedIdentity"],
  "Management Groups": ["Microsoft.Management"],
  "Media Services": ["Microsoft.Media"],
  "Microsoft Defender Advanced Threat Protection": ["Microsoft.WindowsDefenderATP"],
  "Microsoft Sentinel": ["Microsoft.SecurityInsights"],
  "Network Function Manager": ["Microsoft.HybridNetwork"],
  "Network Watcher": ["Microsoft.Network"],
  "Notification Hubs": ["Microsoft.NotificationHubs"],
  "Object Store": ["Microsoft.ObjectStore"],
  "Power BI Embedded": ["Microsoft.PowerBIDedicated"],
  "Power BI": ["Microsoft.PowerBI"],
  "Power Platform": ["Microsoft.PowerPlatform"],
  "SAP HANA on Azure Large Instances": ["Microsoft.HanaOnAzure"],
  "Scheduler": ["Microsoft.Scheduler"],
  "Security Center": ["Microsoft.Security"],
  "Service Bus": ["Microsoft.ServiceBus"],
  "Service Fabric": ["Microsoft.ServiceFabric"],
  "SQL Server on Azure Virtual Machines": ["Microsoft.SqlVirtualMachine"],
  "SQL Server registry": ["Microsoft.AzureData"],
  "Storage": ["Microsoft.Storage","Microsoft.StorageSync"],
  "StorSimple": ["Microsoft.HybridData","Microsoft.StorSimple"],
  "Token": ["Microsoft.Token"],
  "Traffic Manager": ["Microsoft.Network"],
  "Virtual Machine Scale Sets": ["Microsoft.Compute"],
  "Virtual Machines": ["Microsoft.Compute"],
  "Virtual Network NAT": ["Microsoft.Network"],
  "Virtual Network": ["Microsoft.Network"],
  "Virtual networks managed by PaaS services": ["Microsoft.ManagedNetwork"],
  "Virtual WAN": ["Microsoft.Network"],
  "VPN Gateway": ["Microsoft.Network"],
  "Windows 10 IoT Core Services": ["Microsoft.WindowsIoT"]
};

const ResilientServices = [
  "Azure Backup",
  "Azure DNS: Azure DNS Private Zones",
  "Azure DNS: Azure DNS Private Resolver",
  "Azure Public IP",
  "Service Bus",
  "Service Fabric",
  "Storage",
  "Azure Data Lake Storage Gen2",
  "Virtual Machine Scale Sets",
  "Virtual Machines",
  "Virtual Network",
  "VPN Gateway",
  "Azure Active Directory Domain Services",
  "API Management",
  "Azure App Configuration",
  "App Service",
  "App Service Certificates",
  "Azure Bastion",
  "Batch",
  "Azure Cache for Redis",
  "Azure Cognitive Search",
  "Azure Container Apps",
  "Container Instances",
  "Container Registry",
  "Azure Data Explorer",
  "Data Factory",
  "Azure Database for MySQL",
  "Azure Database for PostgreSQL",
  "Azure DDoS Protection",
  "Azure Disk Encryption",
  "Event Grid",
  "Azure Firewall",
  "Azure Firewall Manager",
  "Azure Functions",
  "HDInsight",
  "Azure IoT Hub",
  "Azure Kubernetes Service (AKS)",
  "Logic Apps",
  "Azure Monitor",
  "Network Watcher",
  "Azure Network Watcher: Traffic Analytics",
  "Notification Hubs",
  "Azure Private Link",
  "Azure Route Server",
  "Azure Stream Analytics",
  "SQL Server on Azure Virtual Machines",
  "Virtual WAN",
  "Azure Web Application Firewall",
  "Power BI Embedded",
  "Automation",
  "Azure HPC Cache",
  "Azure IoT Hub Device Provisioning Service",
  "Azure NetApp Files",
  "Azure Red Hat OpenShift",
  "Azure Managed Instance for Apache Cassandra",
  "Azure Active Directory",
  "Microsoft Defender Advanced Threat Protection",
  "Azure Advisor",
  "Azure Blueprints",
  "Azure Bot Service",
  "Content Delivery Network",
  "Cost Management and Billing",
  "Azure DNS",
  "Azure Front Door Service",
  "Data Protection",
  "Azure Lighthouse",
  "Azure Managed Applications",
  "Azure Maps",
  "Azure Peering Service",
  "Azure Performance Diagnostics",
  "Azure Policy",
  "Azure portal",
  "Azure Resource Graph",
  "Azure Stack Edge",
  "Traffic Manager",
  "Customer Lockbox for Microsoft Azure",
  "Enterprise Knowledge Graph",
  "Microsoft Sentinel"
];

// for each service in ResilientServices
// if service is not in ServiceToRP
// print service

for (const service of ResilientServices) {
  if (!ServiceToRP[service]) {
    console.log(service);
  } else {
    for (const rp of ServiceToRP[service]) {
      if (!AliasedRPs.includes(rp)) {
        console.log(`${service} - ${rp}`);
      }
    }
  }
}


